# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='轮播图标题')),
                ('url', models.CharField(max_length=128, verbose_name='轮播图图片url')),
                ('new', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.News', verbose_name='轮播的新闻id')),
            ],
            options={
                'verbose_name': '轮播广告表',
                'verbose_name_plural': '轮播广告表',
                'db_table': 'tb_slide_show',
            },
        ),
    ]
