# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-01 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20190501_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide_image',
            name='url',
            field=models.CharField(max_length=128, verbose_name='轮播图图片url'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=256, verbose_name='用户头像路径'),
        ),
    ]
