# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_slide_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide_image',
            name='is_recommend',
            field=models.BooleanField(default=False, verbose_name='图片是否显示'),
        ),
    ]
