# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-02 12:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20190501_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='index_image_url',
            field=models.CharField(max_length=256, null=True, verbose_name='新闻索引图片路径'),
        ),
        migrations.AlterField(
            model_name='news',
            name='index_image_url_list',
            field=models.CharField(max_length=256, null=True, verbose_name='新闻索引图片路径'),
        ),
        migrations.AlterField(
            model_name='news',
            name='source_avatar_url',
            field=models.CharField(default='null', max_length=256, verbose_name='来源用户的头像'),
        ),
    ]
