# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-12 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_slide_image_is_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_spider',
            field=models.BooleanField(default=True, verbose_name='是否是爬取的新闻'),
        ),
        migrations.AddField(
            model_name='news',
            name='source_avatar_url',
            field=models.ImageField(default='null', upload_to='', verbose_name='来源用户的头像'),
        ),
    ]
