# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-03 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190502_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_collection',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='标记是否删除'),
        ),
    ]
