# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190412_2015'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_keywords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_wrods', models.CharField(max_length=128, verbose_name='搜索关键字')),
                ('search_times', models.IntegerField(verbose_name='搜索次数')),
            ],
            options={
                'verbose_name_plural': ' 搜索关键字表',
                'verbose_name': ' 搜索关键字表',
                'db_table': 'tb_search_keywords',
            },
        ),
    ]
