# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-04-15 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_search_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(db_column='password_md5', max_length=128, verbose_name='用户密码'),
        ),
    ]
