# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-14 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20190504_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=254, unique=True, verbose_name='新闻标题'),
        ),
    ]
