# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-19 22:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20190514_2308'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search_keywords',
            old_name='key_wrods',
            new_name='key_words',
        ),
    ]
